# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Rafalskaia
                                 A QGIS plugin
 "Плагин для создания тепловых карт плотности точек"
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-05
        copyright            : (C) 2025 by Rafalskaya Olga
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Rafalskaia class from file Rafalskaia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rafalakaia import Rafalskaia
    return Rafalskaia(iface)
